/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.testng.annotations.*;

import static org.testng.Assert.*;


public class AppTest {


    @BeforeTest
    public void setUp() {
        System.out.println(new Object() {
        }.getClass().getEnclosingMethod().getName());

    }


    @Test
    public void testingExpression() {
        System.out.println("Test Executed");
    }

    @AfterTest
    public void tearDown() {
        System.out.println(new Object() {
        }.getClass().getEnclosingMethod().getName());
    }

}
